services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline2
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data  # 将数据存储到当前目录下的 postgres_data 文件夹
    user: "postgres:postgres"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8181:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/outline2  # 使用postgres服务的名称
      - KC_DB_USERNAME=user  # PostgreSQL的用户名
      - KC_DB_PASSWORD=pass  # PostgreSQL的密码
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_PROXY=edge  # 告诉Keycloak在使用代理时启用代理模式
      - KC_HTTPS=false  # 确保Keycloak知道请求是通过HTTPS协议来的
      - KC_HOSTNAME_STRICT=false  # 禁用严格主机名检查
      - KC_HOSTNAME=http://kc.localhost:8181
      - KC_TRANSACTION_LOGS_PATH=/opt/keycloak/data/transaction-logs
      - KC_LOGLEVEL=debug
    command: start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak_data:/opt/keycloak/data
#      - ./my-custom-theme:/opt/keycloak/themes/my-custom-theme
        #- ./keycloak_logs:/opt/keycloak/standalone/log
    depends_on:
      - postgres  # 确保 PostgreSQL 在 Keycloak 之前启动
volumes:
  postgres_keycloak:
